### ISSUE TITLE
Look for humans.txt

### ISSUE THREAD

**Issue by nil0x42** [yeswehack/yeswehack_vdp_finder#1]
Some websites have a security section in humans.txt, mentioning a VDP, and no security.txt.

In cases where `security.txt` & `.well-known/sexurity.txt` are not present, it might be interesting to display the contents of `humans.txt` when available.

**Comment by B-i-t-K** [comment]
Sorry for the late reply,

We think that the number of website implementing human.txt while ignoring security.txt is too low to justify the implementation of such a feature. We don't want to risk to trigger more false positive.
